# Generated by Django 3.0.3 on 2020-03-29 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hatim",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reader",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Имя"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Juz",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Свободен"), (2, "Читается"), (3, "Завершен")],
                        default=1,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "hatim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hatim_bot.Hatim",
                        verbose_name="Хатим",
                    ),
                ),
                (
                    "reader",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hatim_bot.Reader",
                        verbose_name="Читает",
                    ),
                ),
            ],
        ),
    ]
