# Generated by Django 3.0.3 on 2020-11-12 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hatim_bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Значение"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="juz",
            options={"ordering": ["hatim", "number"]},
        ),
        migrations.RemoveField(
            model_name="juz",
            name="reader",
        ),
        migrations.RemoveField(
            model_name="reader",
            name="name",
        ),
        migrations.AddField(
            model_name="hatim",
            name="finished",
            field=models.BooleanField(default=False, verbose_name="Завершено"),
        ),
        migrations.AddField(
            model_name="juz",
            name="number",
            field=models.PositiveSmallIntegerField(null=True, verbose_name="Номер"),
        ),
        migrations.AddField(
            model_name="reader",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="reader",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AddField(
            model_name="reader",
            name="read_counter",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Прочитано глав"
            ),
        ),
        migrations.AddField(
            model_name="reader",
            name="reading_days",
            field=models.FloatField(default=0, verbose_name="Сколько дней читал"),
        ),
        migrations.AddField(
            model_name="reader",
            name="take_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата взятия главы"
            ),
        ),
        migrations.AddField(
            model_name="reader",
            name="taken_juz",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hatim_bot.Juz",
                verbose_name="Взял главу",
            ),
        ),
        migrations.AddField(
            model_name="reader",
            name="tg_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Telegram ID"
            ),
        ),
        migrations.AddField(
            model_name="reader",
            name="username",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Username TG"
            ),
        ),
    ]
