repos:
    -   repo: https://github.com/ambv/black
        rev: 22.3.0
        hooks:
        - id: black
          language_version: python3
    -   repo: https://github.com/timothycrosley/isort
        rev: 5.9.3
        hooks:
        -   id: isort
            language_version: python3
            args: ["--profile", "black"]
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 4.0.1
        hooks:
        - id: flake8