# Generated by Django 3.0.3 on 2020-11-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mufteam_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='homework',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
