# Generated by Django 3.0.3 on 2020-11-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_int', models.CharField(max_length=100, verbose_name='Логин')),
                ('reg_date', models.DateTimeField(verbose_name='Дата регистрации')),
            ],
        ),
    ]
