# Generated by Django 3.0.3 on 2020-02-18 07:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="break",
            options={
                "ordering": ["start_time"],
                "verbose_name": "Перемена",
                "verbose_name_plural": "Перемены",
            },
        ),
        migrations.AlterModelOptions(
            name="day",
            options={
                "verbose_name": "День недели",
                "verbose_name_plural": "Дни недели",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["start_time"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "verbose_name": "Модель расписания",
                "verbose_name_plural": "Модели расписаний",
            },
        ),
        migrations.RemoveField(
            model_name="day",
            name="schedule",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="breaks",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="lessons",
        ),
        migrations.AddField(
            model_name="break",
            name="schedule",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.Schedule",
                verbose_name="Расписание",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="schedule",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.Schedule",
                verbose_name="Расписание",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="day",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.Day",
                to_field="number",
                verbose_name="День недели",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="day",
            name="number",
            field=models.PositiveSmallIntegerField(
                default=0,
                unique=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        7, "Введите корректный номер дня"
                    ),
                    django.core.validators.MinValueValidator(
                        1, "Введите корректный номер дня"
                    ),
                ],
                verbose_name="День недели (1-7)",
            ),
            preserve_default=False,
        ),
    ]
