# Generated by Django 3.0.3 on 2020-02-18 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0005_auto_20200218_1036"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="schedule",
        ),
        migrations.AddField(
            model_name="schedule",
            name="day",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.Day",
                verbose_name="Расписание",
            ),
        ),
    ]
