# Generated by Django 3.0.3 on 2020-02-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0006_auto_20200218_1255"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="day",
        ),
        migrations.AddField(
            model_name="day",
            name="schedule",
            field=models.ManyToManyField(
                blank=True, null=True, to="schedule.Schedule", verbose_name="Расписание"
            ),
        ),
    ]
