# Generated by Django 3.0.3 on 2020-02-18 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20200218_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='schedule',
        ),
        migrations.AddField(
            model_name='day',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.Schedule', verbose_name='Расписание'),
        ),
    ]
